<?php
declare(strict_types=1);

/*
 * RBAC Permission Matrix
 * Access levels: 'full' (CRUD), 'view' (read-only index), 'own' (view own records only),
 *               'participate' (view + create), 'report' (view + create), 'no' (blocked)
 * Write operations (create/edit/delete) require 'full'.
 * 'participate' and 'report' allow create but not edit/delete.
 */

$MODULE_ROUTES = [
    'dashboard'           => 'dashboard',
    'alerts/low-stock'    => 'inventory_alerts',
    'alerts/expiry'       => 'inventory_alerts',
    'reports'             => 'reports',
    'reports/view'        => 'reports',
    'reports/print'       => 'reports',
    'reports/export'      => 'reports',
    'settings/backup'     => 'backup',
    'settings/restore'    => 'backup',
    'suppliers'           => 'suppliers',
    'suppliers/create'    => 'suppliers',
    'suppliers/edit'      => 'suppliers',
    'suppliers/delete'    => 'suppliers',
    'suppliers/deliveries'          => 'suppliers',
    'suppliers/delivery/create'     => 'suppliers',
    'suppliers/delivery/edit'       => 'suppliers',
    'suppliers/delivery/delete'     => 'suppliers',
    'materials/raw'                 => 'materials',
    'materials/raw/create'          => 'materials',
    'materials/raw/edit'            => 'materials',
    'materials/raw/delete'          => 'materials',
    'materials/packaging'           => 'materials',
    'materials/packaging/create'    => 'materials',
    'materials/packaging/edit'      => 'materials',
    'materials/packaging/delete'    => 'materials',
    'production'                    => 'production',
    'production/create'             => 'production',
    'production/edit'               => 'production',
    'production/delete'             => 'production',
    'production/label'              => 'production',
    'finished-goods'                => 'finished_goods',
    'finished-goods/create'         => 'finished_goods',
    'finished-goods/edit'           => 'finished_goods',
    'finished-goods/delete'         => 'finished_goods',
    'prices'                        => 'pricing',
    'prices/save'                   => 'pricing',
    'payroll'                       => 'payroll',
    'payroll/generate'              => 'payroll',
    'payroll/pay'                   => 'payroll',
    'payroll/pay-staff'             => 'payroll',
    'payroll/revert'                => 'payroll',
    'payroll/edit'                  => 'payroll',
    'payroll/delete'                => 'payroll',
    'payroll/settings'              => 'payroll',
    'payroll/report'                => 'payroll',
    'payroll/report/print'          => 'payroll',

    'workers'                       => 'workers',
    'workers/create'                => 'workers',
    'workers/store'                 => 'workers',
    'workers/edit'                  => 'workers',
    'workers/update'                => 'workers',
    'workers/delete'                => 'workers',
    'workers/import'                => 'workers',
    'workers/import-store'          => 'workers',
    'workers/template'              => 'workers',

    'worker-shifts'                 => 'worker_shifts',
    'worker-shifts/create'          => 'worker_shifts',
    'worker-shifts/store'           => 'worker_shifts',
    'worker-shifts/edit'            => 'worker_shifts',
    'worker-shifts/update'          => 'worker_shifts',
    'worker-shifts/delete'          => 'worker_shifts',
    'worker-shifts/bulk'            => 'worker_shifts',

    'accounting'                    => 'accounting',
    'accounting/print-report'       => 'accounting',

    'quality'                       => 'quality',
    'quality/create'                => 'quality',
    'quality/edit'                  => 'quality',
    'quality/delete'                => 'quality',
    'quality/traceability'          => 'quality',
    'certifications'                => 'certifications',
    'certifications/create'         => 'certifications',
    'certifications/edit'           => 'certifications',
    'certifications/delete'         => 'certifications',
    'customers'                     => 'customers',
    'customers/create'              => 'customers',
    'customers/edit'                => 'customers',
    'customers/delete'              => 'customers',
    'sales'                         => 'sales',
    'sales/create'                  => 'sales',
    'sales/edit'                    => 'sales',
    'sales/delete'                  => 'sales',
    'sales/receipt'                 => 'sales',
    'invoicing'                     => 'invoicing',
    'invoicing/create'              => 'invoicing',
    'invoicing/edit'                => 'invoicing',
    'invoicing/delete'              => 'invoicing',
    'safety'                        => 'safety',
    'safety/create'                 => 'safety',
    'safety/edit'                   => 'safety',
    'safety/delete'                 => 'safety',
    'safety/hazards'                => 'hazards',
    'safety/hazards/create'         => 'hazards',
    'safety/hazards/edit'           => 'hazards',
    'safety/hazards/delete'         => 'hazards',
    'safety/accidents'              => 'accidents',
    'safety/accidents/create'       => 'accidents',
    'safety/accidents/edit'         => 'accidents',
    'safety/accidents/delete'       => 'accidents',
    'safety/drills'                 => 'drills',
    'safety/drills/create'          => 'drills',
    'safety/drills/edit'            => 'drills',
    'safety/drills/delete'          => 'drills',
    'permits'                       => 'permits',
    'permits/create'                => 'permits',
    'permits/edit'                  => 'permits',
    'permits/delete'                => 'permits',
    'documents'                     => 'documents',
    'documents/create'              => 'documents',
    'documents/edit'                => 'documents',
    'documents/delete'              => 'documents',
    'documents/download'            => 'documents',
    'staff'                         => 'staff',
    'staff/create'                  => 'staff',
    'staff/edit'                    => 'staff',
    'staff/delete'                  => 'staff',
    'staff/shifts'                  => 'staff',
    'staff/shifts/create'           => 'staff',
    'staff/shifts/edit'             => 'staff',
    'staff/shifts/delete'           => 'staff',
    'staff/attendance'              => 'staff',
    'staff/attendance/form'         => 'staff',
    'staff/attendance/edit'         => 'staff',
    'staff/attendance/delete'       => 'staff',
    'training'                      => 'training',
    'training/create'               => 'training',
    'training/edit'                 => 'training',
    'training/delete'               => 'training',
    'ppe'                           => 'ppe',
    'ppe/create'                    => 'ppe',
    'ppe/edit'                      => 'ppe',
    'ppe/delete'                    => 'ppe',
    'machines'                      => 'machines',
    'machines/create'               => 'machines',
    'machines/edit'                 => 'machines',
    'machines/delete'               => 'machines',
    'maintenance'                   => 'maintenance',
    'maintenance/create'            => 'maintenance',
    'maintenance/edit'              => 'maintenance',
    'maintenance/delete'            => 'maintenance',
    'fat'                           => 'fat',
    'fat/create'                    => 'fat',
    'fat/edit'                      => 'fat',
    'fat/delete'                    => 'fat',
    'waste'                         => 'waste',
    'waste/create'                  => 'waste',
    'waste/edit'                    => 'waste',
    'waste/delete'                  => 'waste',
    'water'                         => 'water',
    'water/usage/create'            => 'water',
    'water/usage/form'              => 'water',
    'water/usage/edit'              => 'water',
    'water/usage/delete'            => 'water',
    'water/test/create'             => 'water',
    'water/test/form'               => 'water',
    'water/test/edit'               => 'water',
    'water/test/delete'             => 'water',
    'power'                         => 'power',
    'power/usage/create'            => 'power',
    'power/usage/form'              => 'power',
    'power/usage/edit'              => 'power',
    'power/usage/delete'            => 'power',
    'power/generator/create'        => 'power',
    'power/generator/form'          => 'power',
    'power/generator/edit'          => 'power',
    'power/generator/delete'        => 'power',
    'improvement'                   => 'improvement',
    'improvement/create'            => 'improvement',
    'improvement/edit'              => 'improvement',
    'improvement/delete'            => 'improvement',
    'supplier-evaluations'          => 'supplier_eval',
    'supplier-evaluations/create'   => 'supplier_eval',
    'supplier-evaluations/edit'     => 'supplier_eval',
    'supplier-evaluations/delete'   => 'supplier_eval',
    'efficiency'                    => 'efficiency',
    'efficiency/create'             => 'efficiency',
    'efficiency/edit'               => 'efficiency',
    'efficiency/delete'             => 'efficiency',
    'sops'                          => 'sops',
    'sops/template/create'          => 'sops',
    'sops/template/edit'            => 'sops',
    'sops/template/delete'          => 'sops',
    'sops/checklist/create'         => 'sops',
    'sops/checklist/edit'           => 'sops',
    'sops/checklist/delete'         => 'sops',
    'sops/template/form'            => 'sops',
    'sops/checklist/form'           => 'sops',
    'users'                         => 'users',
    'users/create'                  => 'users',
    'users/edit'                    => 'users',
    'users/delete'                  => 'users',
    'audit'                         => 'audit',
];

/*
 * Routes deliberately left unmapped (available to every signed-in user because
 * they only ever expose that user's own context):
 *   profile        -- the signed-in user's own account page
 *   notifications  -- factory-wide alerts derived from modules the user can see
 */

$ROLE_PERMISSIONS = [
    'ROLE-001' => [
        'payroll'         => 'full', 'pricing'       => 'full', 'workers' => 'full', 'accounting' => 'full',
        'worker_shifts'   => 'full',
        'dashboard'       => 'full', 'inventory_alerts'=> 'full', 'reports'       => 'full',
        'backup'          => 'full', 'suppliers'     => 'full', 'materials'     => 'full',
        'production'      => 'full', 'finished_goods'=> 'full', 'quality'       => 'full',
        'certifications'  => 'full', 'customers'     => 'full', 'sales'         => 'full',
        'invoicing'       => 'full', 'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'full',
        'documents'       => 'full', 'staff'         => 'full', 'training'      => 'full',
        'ppe'             => 'full', 'machines'      => 'full', 'maintenance'   => 'full',
        'fat'             => 'full', 'waste'         => 'full', 'water'         => 'full',
        'power'           => 'full', 'improvement'   => 'full', 'supplier_eval' => 'full',
        'efficiency'      => 'full', 'sops'          => 'full', 'users'         => 'full',
        'audit'           => 'full',
    ],
    'ROLE-002' => [
        'payroll'         => 'full', 'pricing'       => 'full', 'workers' => 'full', 'accounting' => 'full',
        'worker_shifts'   => 'full',
        'dashboard'       => 'full', 'inventory_alerts'=> 'full', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'full', 'materials'     => 'full',
        'production'      => 'full', 'finished_goods'=> 'full', 'quality'       => 'full',
        'certifications'  => 'full', 'customers'     => 'full', 'sales'         => 'full',
        'invoicing'       => 'no',   'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'full',
        'documents'       => 'full', 'staff'         => 'full', 'training'      => 'full',
        'ppe'             => 'full', 'machines'      => 'full', 'maintenance'   => 'full',
        'fat'             => 'no',   'waste'         => 'full', 'water'         => 'full',
        'power'           => 'full', 'improvement'   => 'full', 'supplier_eval' => 'full',
        'efficiency'      => 'full', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'view',
    ],
    'ROLE-003' => [
        'payroll'         => 'no',   'pricing'       => 'no',   'workers' => 'no',   'accounting' => 'no',
        'worker_shifts'   => 'full',
        'dashboard'       => 'full', 'inventory_alerts'=> 'full', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'view', 'materials'     => 'full',
        'production'      => 'full', 'finished_goods'=> 'full', 'quality'       => 'view',
        'certifications'  => 'no',   'customers'     => 'no',   'sales'         => 'no',
        'invoicing'       => 'no',   'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'view',
        'documents'       => 'view', 'staff'         => 'full', 'training'      => 'full',
        'ppe'             => 'full', 'machines'      => 'view', 'maintenance'   => 'report',
        'fat'             => 'no',   'waste'         => 'view', 'water'         => 'view',
        'power'           => 'view', 'improvement'   => 'participate', 'supplier_eval' => 'no',
        'efficiency'      => 'full', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
    'ROLE-004' => [
        'payroll'         => 'no',   'pricing'       => 'no',   'workers' => 'no',   'accounting' => 'no',
        'worker_shifts'   => 'view',
        'dashboard'       => 'full', 'inventory_alerts'=> 'full', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'full', 'materials'     => 'full',
        'production'      => 'view', 'finished_goods'=> 'full', 'quality'       => 'no',
        'certifications'  => 'no',   'customers'     => 'no',   'sales'         => 'no',
        'invoicing'       => 'no',   'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'no',
        'documents'       => 'view', 'staff'         => 'view', 'training'      => 'own',
        'ppe'             => 'view', 'machines'      => 'no',   'maintenance'   => 'no',
        'fat'             => 'no',   'waste'         => 'view', 'water'         => 'view',
        'power'           => 'view', 'improvement'   => 'no',   'supplier_eval' => 'full',
        'efficiency'      => 'view', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
    'ROLE-005' => [
        'payroll'         => 'no',   'pricing'       => 'no',   'workers' => 'no',   'accounting' => 'no',
        'worker_shifts'   => 'view',
        'dashboard'       => 'full', 'inventory_alerts'=> 'view', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'view', 'materials'     => 'no',
        'production'      => 'view', 'finished_goods'=> 'view', 'quality'       => 'full',
        'certifications'  => 'full', 'customers'     => 'no',   'sales'         => 'no',
        'invoicing'       => 'no',   'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'full',
        'documents'       => 'full', 'staff'         => 'view', 'training'      => 'full',
        'ppe'             => 'full', 'machines'      => 'no',   'maintenance'   => 'no',
        'fat'             => 'no',   'waste'         => 'view', 'water'         => 'view',
        'power'           => 'view', 'improvement'   => 'full', 'supplier_eval' => 'no',
        'efficiency'      => 'full', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
    'ROLE-006' => [
        'payroll'         => 'no',   'pricing'       => 'full', 'workers' => 'no',   'accounting' => 'no',
        'worker_shifts'   => 'no',
        'dashboard'       => 'full', 'inventory_alerts'=> 'view', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'no',   'materials'     => 'no',
        'production'      => 'no',   'finished_goods'=> 'view', 'quality'       => 'no',
        'certifications'  => 'no',   'customers'     => 'full', 'sales'         => 'full',
        'invoicing'       => 'full', 'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'no',
        'documents'       => 'view', 'staff'         => 'own',  'training'      => 'own',
        'ppe'             => 'own',  'machines'      => 'no',   'maintenance'   => 'no',
        'fat'             => 'no',   'waste'         => 'no',   'water'         => 'no',
        'power'           => 'no',   'improvement'   => 'no',   'supplier_eval' => 'no',
        'efficiency'      => 'no',   'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
    'ROLE-007' => [
        'payroll'         => 'full', 'pricing'       => 'no',   'workers' => 'full', 'accounting' => 'full',
        'worker_shifts'   => 'view',
        'dashboard'       => 'full', 'inventory_alerts'=> 'view', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'view', 'materials'     => 'view',
        'production'      => 'no',   'finished_goods'=> 'view', 'quality'       => 'no',
        'certifications'  => 'no',   'customers'     => 'view', 'sales'         => 'view',
        'invoicing'       => 'full', 'safety'        => 'full', 'hazards'       => 'view',
        'accidents'       => 'view', 'drills'        => 'view', 'permits'       => 'no',
        'documents'       => 'view', 'staff'         => 'view', 'training'      => 'view',
        'ppe'             => 'view', 'machines'      => 'no',   'maintenance'   => 'no',
        'fat'             => 'no',   'waste'         => 'view', 'water'         => 'view',
        'power'           => 'view', 'improvement'   => 'no',   'supplier_eval' => 'no',
        'efficiency'      => 'view', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
    'ROLE-008' => [
        'payroll'         => 'no',   'pricing'       => 'no',   'workers' => 'no',   'accounting' => 'no',
        'worker_shifts'   => 'no',
        'dashboard'       => 'full', 'inventory_alerts'=> 'view', 'reports'       => 'view',
        'backup'          => 'no',   'suppliers'     => 'no',   'materials'     => 'no',
        'production'      => 'view', 'finished_goods'=> 'no',   'quality'       => 'no',
        'certifications'  => 'no',   'customers'     => 'no',   'sales'         => 'no',
        'invoicing'       => 'no',   'safety'        => 'full', 'hazards'       => 'full',
        'accidents'       => 'full', 'drills'        => 'full', 'permits'       => 'view',
        'documents'       => 'view', 'staff'         => 'own',  'training'      => 'own',
        'ppe'             => 'full', 'machines'      => 'full', 'maintenance'   => 'full',
        'fat'             => 'full', 'waste'         => 'full', 'water'         => 'full',
        'power'           => 'full', 'improvement'   => 'participate', 'supplier_eval' => 'no',
        'efficiency'      => 'full', 'sops'          => 'no',   'users'         => 'no',
        'audit'           => 'no',
    ],
];

function getModuleForRoute(string $route): ?string {
    global $MODULE_ROUTES;
    return $MODULE_ROUTES[$route] ?? null;
}

function getAccess(string $roleId, string $module): string {
    global $ROLE_PERMISSIONS;
    return $ROLE_PERMISSIONS[$roleId][$module] ?? 'no';
}

function can(string $module): bool {
    $u = currentUser();
    if (!$u) return false;
    return getAccess($u['role_id'], $module) !== 'no';
}

function canEdit(string $module): bool {
    $u = currentUser();
    if (!$u) return false;
    return getAccess($u['role_id'], $module) === 'full';
}

function canCreate(string $module): bool {
    $u = currentUser();
    if (!$u) return false;
    $level = getAccess($u['role_id'], $module);
    return in_array($level, ['full', 'participate', 'report'], true);
}
